### PR TITLE
Create callback event after component loads

### PR DESCRIPTION
**Pull request by henriquehbr**
- Implement a `on:loaded` event with `createEventDispatcher` that
  triggers after the component has been loaded
- Bump dependencies
- Add `eslint-plugin-svelte3` to avoid eslint warning about undeclared
  variables between `<script>` and `<script context="module">`
- Remove `.eslintignore` as it isn't being used

### CODE REVIEW

**Comment by kaisermann** [comment]
@henriquehbr I'm willing to merge this PR, but I think `on:load` would be a better fit, think it as the equivalent of `window.onload`. Also, the docs need to be updated with the new feature.

**Comment by henriquehbr** [comment]
Done!

**Comment by dmgolembiowski** [comment]
@henriquehbr's Thank you! This is a super useful feature.

**Comment by kaisermann** [comment]
Released in `v1.5.0`, sorry for taking so long 😁

**Comment by kaisermann** [comment]
Thanks @henriquehbr!

**Pull request merged**
